// src/utils/questionBank.js
// Exhaustive role-specific question bank with 3-tier experience levels:
//   - fresher (0-1 yr): foundational concepts, definitions, basic usage
//   - junior (1-3 yr): hands-on, trade-offs, intermediate patterns
//   - senior (4+ yr): deep systems, architecture decisions, failure modes, leadership
//
// Each role has 25+ unique questions per level (75+ total per role).
// The question engine tracks used questions per session to NEVER repeat within a session.

const QUESTION_BANK = {

  // ────────────────────────────────────────────────────────────
  // JAVA DEVELOPER
  // ────────────────────────────────────────────────────────────
  'Java Developer': {
    fresher: [
      "What is the difference between JDK, JRE, and JVM?",
      "Explain the four pillars of Object-Oriented Programming with Java examples.",
      "What is the difference between ArrayList and LinkedList? When would you use each?",
      "Explain method overloading vs method overriding in Java.",
      "What are Java access modifiers? Explain public, private, protected, and package-private.",
      "What is a constructor? Can a constructor be private? When would you make it private?",
      "What is the difference between == and .equals() in Java?",
      "Explain what an interface is in Java and how it differs from an abstract class.",
      "What is exception handling in Java? Explain try, catch, finally, throw, and throws.",
      "What is the Java Collections Framework? Name the main interfaces and their implementations.",
      "What is autoboxing and unboxing in Java?",
      "Explain the difference between Stack and Queue data structures.",
      "What is a Java String? Why is String immutable in Java?",
      "What is the difference between checked and unchecked exceptions?",
      "What is a static method or variable in Java? When would you use static?",
      "What is the purpose of the 'final' keyword in Java (variable, method, class)?",
      "Explain what a HashMap is and how it stores key-value pairs.",
      "What is a for-each loop? How does it differ from a traditional for loop?",
      "What is the difference between an Iterator and a ListIterator?",
      "Explain what garbage collection means in Java at a high level.",
      "What is a functional interface in Java? Give an example.",
      "What does the 'this' keyword refer to in Java?",
      "What is the difference between throw and throws in Java?",
      "Explain what polymorphism means with a real-world Java example.",
      "What is the purpose of the java.lang.Object class? Name three of its methods.",
    ],
    junior: [
      "How does Java's HashMap internally work? Explain hashing, collisions, and rehashing.",
      "Explain Java's Stream API: how do map(), filter(), and reduce() work together?",
      "What is the difference between Comparable and Comparator in Java?",
      "Explain what a thread is in Java and how you create one. What is the difference between Runnable and Thread?",
      "What is a synchronized method in Java? What problem does it solve?",
      "Explain Java Generics: what is type erasure and why does it exist?",
      "What is the difference between fail-fast and fail-safe iterators?",
      "How does Java's try-with-resources statement work? What is AutoCloseable?",
      "Explain method references in Java 8: what are the four types?",
      "What is the Optional class in Java? How does it help prevent NullPointerException?",
      "How does Spring's dependency injection work? Compare constructor injection vs field injection.",
      "What is the difference between @Component, @Service, @Repository in Spring?",
      "Explain lazy loading vs eager loading in Hibernate/JPA.",
      "What is the N+1 problem in ORM frameworks? How do you solve it?",
      "Explain the differences between HashMap, TreeMap, and LinkedHashMap.",
      "What is the Java Memory Model? What does 'volatile' guarantee?",
      "How does the StringBuilder class differ from String concatenation for performance?",
      "Explain checked vs unchecked exceptions from a design perspective: when to use each?",
      "What is a deadlock? Write a simple scenario that causes one in Java.",
      "Explain the difference between interface default methods and abstract class methods in Java 8+.",
      "What is CompletableFuture in Java? How does it differ from Future?",
      "Explain Spring's transaction management with @Transactional — what happens at the proxy level?",
      "How does Java's garbage collector identify objects eligible for collection?",
      "What is the difference between List.of() and new ArrayList() in Java 9+?",
      "Explain the Strategy design pattern. Write a Java example using an interface.",
    ],
    senior: [
      "Explain the JVM memory model in detail: heap generations, metaspace, Eden/Survivor spaces.",
      "Compare G1GC vs ZGC vs Shenandoah for low-latency JVM applications. What trade-offs guide your choice?",
      "How does ConcurrentHashMap achieve thread safety without locking the entire map? Explain CAS operations.",
      "Design a thread-safe, non-blocking LRU cache in Java using ConcurrentHashMap and atomic operations.",
      "Explain Java's happens-before guarantee. How does synchronized vs volatile vs StampedLock differ?",
      "How would you diagnose and resolve a production memory leak in a Java microservice?",
      "Explain Spring's bean lifecycle in detail: all callbacks, BeanPostProcessor hooks, and scope interactions.",
      "How do you design a high-throughput event processing pipeline using Java CompletableFuture and ForkJoinPool?",
      "Explain the differences between JPA pessimistic locking and optimistic locking at scale.",
      "How would you implement a distributed rate limiter in Java using Redis and Lua scripts?",
      "Describe your approach to tuning JVM GC pause times for a 99.9th-percentile latency SLA.",
      "Explain Java's Project Loom virtual threads: how do they change the I/O threading model?",
      "How would you implement a custom Spring Security filter chain for multi-tenant JWT authentication?",
      "Explain the differences between Java Records, sealed classes, and traditional class hierarchies for domain modeling.",
      "How would you architect a reactive, non-blocking REST API using Spring WebFlux and Project Reactor?",
      "Describe how you'd use JMH (Java Microbenchmark Harness) to measure and optimize a critical code path.",
      "Explain how you'd design a Java-based distributed job scheduler with leader election using ZooKeeper.",
      "What are the trade-offs between using Kafka Streams vs Flink for stateful stream processing in Java?",
      "Explain circular dependency in Spring and how Spring resolves it — and why constructor injection prevents it.",
      "How does Java's ClassLoader hierarchy work? When would you write a custom ClassLoader?",
      "Design a resiliency pattern for a Java microservice calling an unreliable external API (circuit breaker, retry, bulkhead).",
      "How would you profile a Java application to identify CPU hotspots? Name tools and methodology.",
      "Explain the difference between fine-grained and coarse-grained locking strategies for concurrent data structures.",
      "How do you implement event sourcing with Axon Framework in a Java microservice architecture?",
      "Explain Java's SPI (Service Provider Interface) mechanism and how it enables plugin-style extensibility.",
    ],
  },

  // ────────────────────────────────────────────────────────────
  // PYTHON DEVELOPER
  // ────────────────────────────────────────────────────────────
  'Python Developer': {
    fresher: [
      "What is the difference between a list and a tuple in Python?",
      "Explain Python's mutable vs immutable types with examples.",
      "What are Python dictionaries? How do you iterate over keys, values, and items?",
      "What is a Python function? What are *args and **kwargs?",
      "Explain the difference between 'is' and '==' in Python.",
      "What are Python list comprehensions? Write an example that squares even numbers.",
      "What is exception handling in Python? Give an example with try/except/finally.",
      "What is the difference between a module and a package in Python?",
      "Explain Python's indentation rules and why they matter.",
      "What are Python decorators at a basic level? Give a simple example.",
      "What is the global interpreter lock (GIL)? What does it mean simply?",
      "What is the difference between append() and extend() for Python lists?",
      "How do you open and read a file in Python? What is 'with open' and why use it?",
      "What are Python sets? How are they different from lists and dicts?",
      "Explain the range() function in Python.",
      "What is string formatting in Python? Show f-strings, .format(), and % formatting.",
      "What is a lambda function in Python?",
      "Explain what None means in Python and how it differs from 0, False, or ''.",
      "What is the difference between break, continue, and pass in loops?",
      "What does the __init__ method do in a Python class?",
      "How do you handle default arguments in Python functions?",
      "What is the difference between local and global scope in Python?",
      "What is slicing in Python? Show slice notation examples.",
      "What are Python's built-in functions? Name five and explain what they do.",
      "What is PEP 8? Why does it matter?",
    ],
    junior: [
      "Explain Python generators and the yield keyword. How do they differ from regular functions?",
      "How do Python decorators work under the hood? Write a retry decorator from scratch.",
      "What is Python's context manager protocol (__enter__/__exit__)? Write a custom one.",
      "Explain Python's GIL: when does threading work well, and when should you use multiprocessing?",
      "What are Python metaclasses? When would you actually use one?",
      "Explain the difference between shallow copy and deep copy in Python.",
      "How does Python's asyncio event loop work for I/O-bound tasks?",
      "Explain Python's memory management: reference counting and the cyclic garbage collector.",
      "What is the difference between @classmethod, @staticmethod, and instance methods?",
      "Explain Python's MRO (Method Resolution Order) with a diamond inheritance example.",
      "How do you use functools.lru_cache and functools.partial effectively?",
      "What is the difference between a closure and a class for encapsulating state?",
      "Explain how Django's ORM builds queries lazily. What is a QuerySet?",
      "How would you design a Flask or FastAPI middleware for request authentication?",
      "Explain type hints in Python: what does mypy check and what are the limitations?",
      "What are Python dataclasses? How do they differ from NamedTuple and regular classes?",
      "How does Python's 'with' statement interact with the context manager protocol?",
      "What is the difference between threading.Lock and threading.RLock?",
      "Explain what pickling is in Python and its security implications.",
      "What are Python's __slots__? When do they improve memory efficiency?",
      "How would you implement a simple dependency injection pattern in Python?",
      "Explain the difference between Queue and SimpleQueue in Python's threading module.",
      "What is the walrus operator (:=) and when should you use it?",
      "How does pytest's fixture system work? Explain fixture scope and parametrize.",
      "What are abstract base classes (ABC) in Python and when should you use them?",
    ],
    senior: [
      "How would you design a Python-based distributed task queue system from scratch?",
      "Explain CPython's memory allocator (pymalloc) and how to reduce memory fragmentation.",
      "How do you use Python's cProfile and line_profiler to find and fix a production performance bottleneck?",
      "Explain Python's descriptor protocol (__get__, __set__, __delete__) with a practical caching example.",
      "How would you implement a high-performance async web scraper using asyncio and aiohttp?",
      "Describe your approach to building a production-grade ML model serving API with FastAPI, Pydantic, and async database calls.",
      "How do you implement distributed tracing and structured logging in a Python microservice architecture?",
      "Explain the trade-offs between Celery, RQ, Dramatiq, and APScheduler for Python background task processing.",
      "How would you architect a multi-tenant SaaS application in Django with schema isolation?",
      "Explain Python's import system: how does sys.modules work and how would you write a custom importer?",
      "How do you handle backpressure in an async Python pipeline processing high-volume event streams?",
      "Describe a real scenario where you had to optimize a Python service from 10 RPS to 1000 RPS.",
      "How do you implement zero-downtime deployments for a Python application?",
      "Explain how you'd write a Python C extension module for a CPU-bound bottleneck.",
      "What are the performance implications of using async/await vs threading in Python 3.11+?",
      "How would you implement a distributed lock in Python using Redis?",
      "Explain how to build a resilient Python consumer for Kafka with at-least-once delivery guarantees.",
      "What are the trade-offs between uvicorn, gunicorn, and hypercorn for FastAPI deployments?",
      "How do you securely manage secrets in a Python production environment?",
      "Explain how Protocol types in Python enable structural subtyping (duck typing with type checking).",
      "How would you design a plugin system in Python using setuptools entry_points?",
      "Describe your strategy for testing a complex async Python application with mocks and integration tests.",
      "How does Python's garbage collector handle reference cycles? Explain gc.collect() and gc.disable() use cases.",
      "Explain the WSGI vs ASGI application interface — what changed in the Python web ecosystem?",
      "How would you implement a rate limiter as a Python async middleware using Redis sorted sets?",
    ],
  },

  // ────────────────────────────────────────────────────────────
  // FULL STACK DEVELOPER
  // ────────────────────────────────────────────────────────────
  'Full Stack Developer': {
    fresher: [
      "What is the difference between front-end and back-end development?",
      "Explain what HTML, CSS, and JavaScript each do in a web application.",
      "What is HTTP? What are the common HTTP methods (GET, POST, PUT, DELETE)?",
      "What is a REST API? How does it communicate between a client and a server?",
      "What is JSON? Write an example JSON object for a user profile.",
      "Explain what a database is. What is the difference between SQL and NoSQL?",
      "What is a cookie? How is it different from localStorage and sessionStorage?",
      "What is a CSS flexbox? How does display:flex change element layout?",
      "What is Git? What do the commands init, commit, push, and pull do?",
      "What is npm? What is package.json used for?",
      "Explain what Node.js is and how it differs from browser JavaScript.",
      "What is React? What problem does a JavaScript framework solve?",
      "What is a primary key in a relational database?",
      "Explain what CORS is and why browsers enforce it.",
      "What is an API endpoint? Give an example URL and explain its parts.",
      "What is the difference between synchronous and asynchronous code in JavaScript?",
      "What is a CSS class vs an ID? When would you use each?",
      "What is responsive design? What is a CSS media query?",
      "Explain what a 404 error means and what a 500 error means.",
      "What is the purpose of a .env file?",
      "What is an ORM and why is it used instead of writing raw SQL?",
      "What is JWT? At a high level, how does it keep users logged in?",
      "What is the difference between POST and PUT HTTP methods?",
      "What is a React component? What is JSX?",
      "What is the role of a web server like Express.js?",
    ],
    junior: [
      "Compare REST vs GraphQL APIs: when would you choose each for a production application?",
      "How would you implement secure JWT-based authentication with refresh token rotation?",
      "Explain database normalization vs denormalization trade-offs for a high-read application.",
      "How would you design a CI/CD pipeline for a full-stack app with staging and production environments?",
      "Explain caching strategies: when do you use Redis vs CDN vs in-memory caching?",
      "How does React's Virtual DOM reconciliation algorithm work?",
      "Explain the difference between useMemo and useCallback. When does each actually improve performance?",
      "How do you handle database schema migrations in production without data loss?",
      "What is XSS (Cross-Site Scripting)? How do you prevent it in a React/Express app?",
      "What is CSRF? How do SameSite cookies and CSRF tokens prevent it?",
      "Explain connection pooling in a Node.js/PostgreSQL application. Why is it critical?",
      "How would you implement pagination for an API returning millions of records?",
      "Explain the differences between server-side rendering (SSR), static generation (SSG), and client-side rendering (CSR).",
      "How do you handle file uploads on both the client side and server side?",
      "What are React hooks? Explain useState, useEffect, and useContext with real use cases.",
      "How would you structure a full-stack project with clear separation of concerns?",
      "Explain how you'd implement optimistic UI updates in a React application.",
      "What are database indexes? Explain when adding an index can slow down writes.",
      "How does a reverse proxy like Nginx differ from Node.js? Why run both?",
      "Explain how environment-specific configuration (dev/staging/prod) works in a Node.js app.",
      "What is WebSocket? How does it differ from HTTP polling for real-time features?",
      "How would you debug a memory leak in a Node.js Express server?",
      "Explain the OAuth 2.0 authorization code flow step by step.",
      "What is the difference between SQL transactions and eventual consistency in NoSQL?",
      "How do you implement role-based access control (RBAC) in an Express.js API?",
    ],
    senior: [
      "How would you migrate a monolithic application to microservices without downtime?",
      "Design a horizontally scalable real-time collaborative editing system (like Google Docs).",
      "Explain the trade-offs between a monorepo and a multi-repo strategy for a full-stack team.",
      "How do you design an API gateway for a microservices architecture with rate limiting, auth, and routing?",
      "Describe your strategy for achieving sub-100ms API response times at high scale.",
      "How would you implement a distributed session store across multiple Node.js instances?",
      "Explain event-driven architecture using message queues (Kafka/RabbitMQ) in a full-stack system.",
      "How do you architect a multi-region deployment for a full-stack SaaS application?",
      "Explain the CQRS and Event Sourcing patterns. When are they worth the complexity?",
      "How do you handle long-running background jobs in a full-stack application without blocking?",
      "Describe your approach to feature flag systems for gradual rollouts at scale.",
      "How would you design a search system using Elasticsearch for a large content platform?",
      "Explain your blue-green and canary deployment strategies for a full-stack application.",
      "How do you design a cost-efficient serverless full-stack application on AWS Lambda?",
      "Explain how you'd implement end-to-end encryption for user data in a full-stack application.",
      "How do you build and maintain a shared design system for multiple full-stack products?",
      "What is your approach to performance budgets and measuring Core Web Vitals in production?",
      "Explain database sharding strategies for a multi-tenant full-stack application at scale.",
      "How would you implement a resilient payment processing system with idempotency guarantees?",
      "Describe your approach to API versioning for a public API with thousands of consumers.",
      "How do you architect observability (logs, metrics, traces) across a full-stack distributed system?",
      "Explain your strategy for zero-downtime database migrations in production.",
      "How would you design a scalable notification system (email, push, SMS) for millions of users?",
      "Describe how you'd implement A/B testing infrastructure in a full-stack application.",
      "How do you structure and manage technical debt in a large full-stack codebase?",
    ],
  },

  // ────────────────────────────────────────────────────────────
  // FRONTEND DEVELOPER
  // ────────────────────────────────────────────────────────────
  'Frontend Developer': {
    fresher: [
      "What is the difference between HTML, CSS, and JavaScript?",
      "Explain the CSS box model: margin, border, padding, content.",
      "What is the DOM? How does JavaScript interact with it?",
      "What is the difference between inline, block, and inline-block elements in CSS?",
      "Explain CSS specificity: how does the browser decide which style to apply?",
      "What is a CSS flexbox? Give an example of centering an element.",
      "What is CSS Grid? How is it different from Flexbox?",
      "What are media queries? Write a simple example for mobile vs desktop.",
      "What is the difference between var, let, and const in JavaScript?",
      "What are JavaScript promises? How do they work?",
      "What is async/await in JavaScript?",
      "Explain what React is and what problem it solves.",
      "What is a React component? What is the difference between a functional and class component?",
      "What is JSX in React?",
      "What is useState in React? Write a simple counter example.",
      "What is an event listener in JavaScript? Give an example.",
      "What is the difference between getElementById and querySelector?",
      "What is localStorage? How is it different from sessionStorage and cookies?",
      "What is responsive design? Why is it important?",
      "Explain what a CSS pseudo-class is (e.g., :hover, :focus).",
      "What is the difference between position: relative, absolute, fixed, and sticky?",
      "What is cross-browser compatibility? Why can it be challenging?",
      "Explain what SASS/SCSS adds on top of regular CSS.",
      "What is a CSS variable (custom property)?",
      "What is the purpose of the meta viewport tag in HTML?",
    ],
    junior: [
      "Explain how React's Virtual DOM diffing algorithm works, and how keys optimize list re-renders.",
      "How do CSS containment, compositing layers, and requestAnimationFrame optimize browser rendering?",
      "Explain the difference between useMemo and useCallback. When does each actually improve performance?",
      "How would you debug and fix a Core Web Vitals regression (high LCP or CLS)?",
      "What are React's useEffect cleanup functions? Why are they critical for preventing memory leaks?",
      "Explain the difference between controlled and uncontrolled components in React.",
      "How does code splitting with React.lazy and Suspense work?",
      "Explain TypeScript generics with a React component example.",
      "What is the React Context API? When should you use it vs external state management?",
      "Explain CSS transitions vs CSS animations — when would you use each?",
      "How do you optimize images for the web (WebP, lazy loading, responsive srcset)?",
      "What is tree shaking? How does Webpack/Vite eliminate dead code?",
      "Explain the difference between event bubbling and event capturing.",
      "How would you implement infinite scroll with React and Intersection Observer?",
      "What is a custom React hook? Write one that debounces an input value.",
      "Explain CSS z-index and stacking contexts — what are common pitfalls?",
      "How would you implement a dark/light theme toggle without CSS-in-JS libraries?",
      "What is WCAG 2.1 accessibility? What are ARIA attributes and when are they needed?",
      "Explain how the browser critical rendering path works: HTML parsing, CSSOM, render tree.",
      "How do you handle global error boundaries in React?",
      "What is the difference between client-side routing (React Router) and server-side routing?",
      "Explain how you'd implement a debounced search input with API calls in React.",
      "How do service workers enable offline functionality in a Progressive Web App?",
      "What are CSS Modules? How do they solve CSS global scope pollution?",
      "Explain prop drilling in React and how to solve it without Redux.",
    ],
    senior: [
      "Describe how you'd architect a micro-frontend platform using Webpack Module Federation.",
      "Explain React Server Components vs Server-Side Rendering: fundamental differences and trade-offs.",
      "How would you architect a design system component library supporting theming, accessibility, and versioning?",
      "Describe your strategy for achieving 90+ Lighthouse scores for a large content-heavy web application.",
      "How do you implement state machines with XState for complex UI workflows?",
      "Explain advanced React patterns: Compound Components, Render Props, and the Observer pattern.",
      "How would you build a real-time collaborative UI (like Figma) with CRDT and WebSockets?",
      "Describe your approach to automated visual regression testing for a frontend codebase.",
      "How do you implement streaming server-sent events (SSE) for a live dashboard?",
      "Explain how you'd design a feature flag system for A/B testing React components.",
      "Describe your strategy for bundle optimization in a large React application with 100+ routes.",
      "How do you implement intelligent prefetching and data hydration strategies for Next.js?",
      "Explain how browser DevTools Performance tab can be used to diagnose a slow React render.",
      "How would you architect a frontend data layer using React Query and optimistic mutations?",
      "Describe how you'd build a headless CMS integration with incremental static regeneration.",
      "How do you implement multi-language internationalization (i18n) in a large React application?",
      "Explain CSS containment (contain: layout paint) and how it improves rendering performance.",
      "How would you design a real-time cursor-sharing feature for a collaborative web tool?",
      "Describe your approach to front-end security: CSP headers, subresource integrity, XSS prevention.",
      "How do you build a robust drag-and-drop system in React using the Pointer Events API?",
      "Explain how to implement virtualized lists (react-virtual/react-window) for 100k+ item datasets.",
      "Describe a strategy for migrating a large legacy jQuery application to React incrementally.",
      "How do you measure and optimize Time to Interactive (TTI) for a JavaScript-heavy SPA?",
      "Explain how custom elements and the Shadow DOM API work in web components.",
      "How would you architect a white-label SaaS frontend that allows per-customer branding?",
    ],
  },

  // ────────────────────────────────────────────────────────────
  // BACKEND DEVELOPER
  // ────────────────────────────────────────────────────────────
  'Backend Developer': {
    fresher: [
      "What is a web server? What does it do?",
      "What are HTTP status codes? Explain 200, 201, 400, 401, 403, 404, and 500.",
      "What is the difference between GET, POST, PUT, PATCH, and DELETE HTTP methods?",
      "What is a REST API? Explain its key principles.",
      "What is JSON? How is it used in APIs?",
      "What is a database? What is the difference between SQL and NoSQL?",
      "What is a primary key vs a foreign key in SQL?",
      "Write a SQL query to get all users where age > 25 ordered by name.",
      "What is an index in a database? Why would you add one?",
      "What is a JOIN in SQL? Explain INNER JOIN vs LEFT JOIN.",
      "What is CRUD? Give an example of each operation with an HTTP method.",
      "What is a middleware in Express.js?",
      "What is authentication vs authorization?",
      "What is a JWT token? What are its three parts?",
      "What is bcrypt? Why do we hash passwords?",
      "What is an environment variable? Why should secrets be stored there?",
      "What is a connection pool in databases?",
      "What is CORS? Why do browsers enforce it?",
      "Explain what a webhook is and how it differs from polling.",
      "What is the purpose of a .gitignore file?",
      "What is a 503 error? What might cause it on a backend server?",
      "What is the difference between PUT and PATCH?",
      "What is an ORM and what problems does it solve?",
      "What is idempotency in HTTP APIs? Give an example.",
      "Explain what a message queue is at a high level.",
    ],
    junior: [
      "How do you design idempotent APIs, and why is idempotency critical for distributed systems?",
      "Explain database indexing strategies: B-tree, hash, and composite indexes — trade-offs?",
      "How would you implement rate limiting for a public API (token bucket vs sliding window)?",
      "Explain the Circuit Breaker pattern and how it prevents cascading failures in microservices.",
      "How do you handle distributed transactions across multiple microservices (Saga pattern)?",
      "How would you optimize a slow database query that's causing production latency spikes?",
      "Explain event sourcing vs traditional CRUD: when is event sourcing worth the complexity?",
      "What is database connection pooling and what happens when the pool is exhausted?",
      "How would you implement pagination with cursor-based pagination vs offset pagination?",
      "Explain the difference between synchronous and asynchronous communication patterns in microservices.",
      "How do you implement request validation and sanitization to prevent SQL injection?",
      "Explain what a database transaction is and the ACID properties.",
      "How would you design an API that handles partial failures gracefully?",
      "Explain how you'd use Redis for session storage and caching in a backend application.",
      "What is API versioning? What are the different versioning strategies and their trade-offs?",
      "How do you handle file uploads and what are the security considerations?",
      "Explain the difference between horizontal and vertical database scaling.",
      "How would you implement a background job processor in Node.js/Express?",
      "What is gRPC? How does it compare to REST for internal microservice communication?",
      "Explain database denormalization: when is it appropriate despite the trade-offs?",
      "How do you log and monitor errors effectively in a production backend application?",
      "What is the Outbox Pattern? How does it solve dual-write consistency in microservices?",
      "Explain how to implement server-sent events (SSE) vs WebSockets for real-time features.",
      "How do you handle configuration management across multiple backend environments?",
      "What are health check endpoints? What should a good /health endpoint return?",
    ],
    senior: [
      "Design a URL shortener service (like bit.ly) that handles 100 million redirects per day.",
      "How would you implement a distributed lock service without a single point of failure?",
      "Explain the CQRS + Event Sourcing pattern. When is the complexity justified?",
      "How do you design a system to guarantee exactly-once processing in a distributed message pipeline?",
      "Describe your approach to database sharding for a multi-tenant SaaS platform at scale.",
      "Explain how you'd implement a real-time leaderboard for 10 million concurrent users using Redis.",
      "How do you design a resilient retry mechanism with exponential backoff and jitter?",
      "Explain leader election using ZooKeeper or etcd for a distributed backend service.",
      "How would you design a distributed caching layer that handles cache stampede and thundering herd?",
      "Describe your architecture for a high-throughput webhook delivery system with at-least-once guarantees.",
      "Explain how service mesh (Istio/Linkerd) handles traffic management, mTLS, and observability.",
      "How would you architect a multi-region active-active deployment with conflict resolution?",
      "Describe how you'd implement a full-text search system using Elasticsearch at scale.",
      "Explain your strategy for versioning data schemas in a distributed event-driven system.",
      "How do you implement request tracing across multiple backend microservices?",
      "Describe a time you solved a production performance crisis — your diagnosis and resolution methodology.",
      "How would you design a streaming data pipeline ingesting 1 million events per second?",
      "Explain the CAP theorem with a concrete production decision you'd make for a specific use case.",
      "How do you design an API gateway from scratch: routing, auth, rate limiting, circuit breaking?",
      "Describe your approach to zero-downtime database migrations on production tables with millions of rows.",
      "How would you architect a content delivery network (CDN) integration for static asset serving?",
      "Explain blue-green deployment vs canary releases for a backend service with breaking API changes.",
      "How do you implement end-to-end encryption for sensitive user data in a backend system?",
      "Describe your strategy for capacity planning and autoscaling a backend cluster.",
      "How would you design an audit logging system for compliance that cannot be tampered with?",
    ],
  },

  // ────────────────────────────────────────────────────────────
  // DATA ANALYST
  // ────────────────────────────────────────────────────────────
  'Data Analyst': {
    fresher: [
      "What is the difference between structured and unstructured data?",
      "What are the five basic SQL commands? Explain each.",
      "What is a GROUP BY clause in SQL? Give an example.",
      "Explain the difference between HAVING and WHERE in SQL.",
      "What is an aggregate function? Name five examples.",
      "What is the difference between INNER JOIN and LEFT JOIN?",
      "What is a NULL value in SQL? How do you handle NULLs?",
      "What is Excel VLOOKUP? When would you use it?",
      "What is the difference between mean, median, and mode?",
      "What is a histogram? What does it tell you about data distribution?",
      "What is a pivot table? Explain how you'd use one.",
      "What is data cleaning? Name three common data quality problems.",
      "What is the difference between quantitative and qualitative data?",
      "What is a bar chart vs a line chart? When would you use each?",
      "What is a KPI? Give three examples of business KPIs.",
      "What is the difference between correlation and causation?",
      "What is a data type? Name five SQL data types.",
      "What is a dashboard? What makes a good business dashboard?",
      "What is the purpose of an ORDER BY clause in SQL?",
      "What is data normalization at a basic level?",
      "What is an outlier? How do you identify one?",
      "What is the difference between a database and a spreadsheet?",
      "What is a subquery in SQL?",
      "What does it mean to 'clean' a dataset?",
      "What is A/B testing at a basic level?",
    ],
    junior: [
      "How do window functions like ROW_NUMBER(), RANK(), and DENSE_RANK() differ in SQL?",
      "Explain how you would handle missing or corrupted data in a large time-series dataset.",
      "What metrics would you define to measure user retention vs churn for a SaaS product?",
      "Explain the difference between A/B testing statistical significance and statistical power.",
      "Explain CTEs (Common Table Expressions) vs subqueries — when is each more appropriate?",
      "How do you detect and handle data quality issues in production analytics pipelines?",
      "Describe how you would build a customer cohort analysis to identify high-value user segments.",
      "What is the difference between a star schema and a snowflake schema in data warehousing?",
      "Explain how you'd design a funnel analysis for a user onboarding flow.",
      "What is the difference between p-value and confidence interval? How do you interpret each?",
      "How would you use Python (pandas) to analyze a dataset with 10 million rows efficiently?",
      "Explain the difference between OLTP and OLAP databases. Which do you use for analytics?",
      "What is data granularity? How does it affect analytics accuracy?",
      "How would you identify a seasonal trend vs. a real business shift in time-series data?",
      "Explain the difference between a left join and a left anti-join in analytical queries.",
      "How do you prioritize which metrics to present to stakeholders?",
      "What is data lineage? Why is it important for analytics reliability?",
      "Explain Pareto analysis (80/20 rule) and how you'd apply it to customer data.",
      "How would you validate the accuracy of a new analytics dashboard?",
      "What is cumulative vs. period-over-period analysis? When do you use each?",
      "Explain how you'd approach an analysis when two data sources give conflicting results.",
      "What is bucketing vs. binning in data analysis? Give an example.",
      "How would you calculate customer lifetime value (CLV) using SQL?",
      "Explain what a surrogate key is in a data warehouse context.",
      "What are slowly changing dimensions (SCD) in data warehousing? Name the types.",
    ],
    senior: [
      "How would you design a metrics framework for a new product launch from scratch?",
      "Explain the difference between experimentation at the user level vs page level — why does it matter for significance?",
      "How do you design a data pipeline to process 10 million daily events into BI dashboards?",
      "Describe your approach to diagnosing a 30% drop in a core business metric.",
      "How do you build a robust experimentation platform to run 50+ A/B tests simultaneously?",
      "Explain the difference between Bayesian and frequentist approaches to A/B testing.",
      "How would you design a self-serve analytics platform for non-technical stakeholders?",
      "Describe how you'd architect a real-time analytics system using Kafka, Flink, and ClickHouse.",
      "Explain how you handle selection bias in user experimentation.",
      "How would you measure the long-term impact of a feature when A/B tests only last 2 weeks?",
      "Describe your approach to defining and maintaining data contracts in a large data ecosystem.",
      "How do you detect and handle sample ratio mismatch (SRM) in experiments?",
      "Explain network effects in experimentation: how do they violate the SUTVA assumption?",
      "How would you build a revenue attribution model across multiple marketing touchpoints?",
      "Describe your approach to building a customer health score model using multiple data signals.",
      "How do you ensure data quality across a distributed data platform with many upstream sources?",
      "Explain your strategy for handling GDPR/privacy compliance in a data analytics platform.",
      "How would you architect a real-time anomaly detection system for business metrics?",
      "Describe your approach to forecasting with seasonality, trend, and external factors.",
      "How do you quantify and communicate the business impact of a data quality improvement?",
      "Explain the trade-offs between pre-aggregated vs. raw event data for analytics.",
      "How would you design a churn prediction model and integrate it into product workflows?",
      "Describe your methodology for stakeholder alignment when data tells a counterintuitive story.",
      "How do you build a data governance framework for a large analytics organization?",
      "Explain how you'd use causal inference methods (DiD, synthetic control) when A/B testing is infeasible.",
    ],
  },

  // ────────────────────────────────────────────────────────────
  // DEVOPS ENGINEER
  // ────────────────────────────────────────────────────────────
  'DevOps Engineer': {
    fresher: [
      "What is DevOps? How does it differ from traditional software development practices?",
      "What is a Linux command line? Name five common shell commands.",
      "What is version control? What is Git and why is it used?",
      "What is Docker? What problem does containerization solve?",
      "What is a Dockerfile? What are the most common instructions?",
      "What is the difference between a Docker image and a Docker container?",
      "What is CI/CD? What does continuous integration mean?",
      "What is YAML? Why is it used in DevOps tooling?",
      "What is a shell script? Write a script that prints 'Hello World'.",
      "What is SSH? How do you connect to a remote server using SSH?",
      "What is a virtual machine vs a container?",
      "What is a port? What is port 80 and port 443 used for?",
      "What is DNS? How does a domain name get resolved to an IP address?",
      "What is a load balancer? What problem does it solve?",
      "What is a firewall? What is a security group in AWS?",
      "What is the difference between TCP and UDP?",
      "What is cron? How do you schedule a job to run every day at midnight?",
      "What is an environment variable? How do you set one in Linux?",
      "What is the purpose of a .gitignore file?",
      "What is a log file? Why are logs important in operations?",
      "What is Nginx? What does a web server do?",
      "What is a REST API health check? What should it return?",
      "What is the difference between dev, staging, and production environments?",
      "What is an S3 bucket in AWS?",
      "What is the difference between chmod and chown in Linux?",
    ],
    junior: [
      "Explain Docker multi-stage builds and how they reduce production image size.",
      "How does Kubernetes handle pod scheduling, auto-scaling, and self-healing?",
      "Compare Terraform vs Ansible: when would you use each for infrastructure management?",
      "How would you set up comprehensive observability (logging, metrics, tracing) for a distributed system?",
      "Explain Kubernetes networking: Services, Ingress controllers, and network policies.",
      "How do you implement secrets management in a containerized production environment?",
      "Describe your approach to disaster recovery and multi-region failover.",
      "Explain the difference between a Kubernetes Deployment, StatefulSet, and DaemonSet.",
      "How would you implement a zero-downtime rolling deployment strategy in Kubernetes?",
      "Explain how Prometheus scrapes metrics and how Grafana visualizes them.",
      "What is Infrastructure as Code (IaC)? What are the benefits over manual provisioning?",
      "Explain how you'd set up a GitHub Actions CI/CD pipeline for a Node.js application.",
      "What is a Helm chart? Why is it used for Kubernetes deployments?",
      "Explain the difference between blue-green and canary deployment strategies.",
      "How do you manage Kubernetes resource requests and limits? What happens when they're not set?",
      "What is a VPC? Explain subnets, route tables, and security groups.",
      "How do you handle configuration drift in infrastructure managed by Terraform?",
      "Explain the difference between pull-based and push-based CI/CD pipelines.",
      "How would you set up centralized logging with the ELK stack?",
      "What is a sidecar pattern in Kubernetes? Give a real example.",
      "How do you implement automated security scanning in a CI/CD pipeline?",
      "Explain what a container registry is and how you'd manage image versioning.",
      "How do you debug a crashed Kubernetes pod?",
      "What is a readiness probe vs a liveness probe in Kubernetes?",
      "How would you implement autoscaling based on custom metrics in Kubernetes?",
    ],
    senior: [
      "Design a CI/CD pipeline for a 50-service microservices platform with independent deployments.",
      "Explain Kubernetes cluster federation and multi-cluster management strategies.",
      "How would you implement GitOps using ArgoCD for a production Kubernetes environment?",
      "Describe your strategy for achieving 99.99% uptime for a globally distributed service.",
      "How do you design a cost optimization strategy for a large AWS/GCP/Azure environment?",
      "Explain how you'd implement chaos engineering practices using tools like Chaos Monkey.",
      "Describe your approach to Kubernetes security hardening: RBAC, NetworkPolicy, OPA/Gatekeeper.",
      "How would you architect a service mesh (Istio) for observability and traffic management?",
      "Explain how you'd implement progressive delivery with feature flags and traffic shifting.",
      "How do you build a self-service infrastructure platform for development teams (Internal Developer Platform)?",
      "Describe your approach to SRE practices: SLOs, SLIs, error budgets, and toil reduction.",
      "How would you design a Kubernetes multi-tenancy model for multiple product teams?",
      "Explain your strategy for database disaster recovery with RPO < 5 minutes and RTO < 30 minutes.",
      "How do you implement eBPF-based network observability in a Kubernetes cluster?",
      "Describe your approach to supply chain security: SLSA framework, SBOM, artifact signing.",
      "How would you migrate a large on-premise data center workload to Kubernetes on AWS EKS?",
      "Explain how you'd implement distributed tracing across 30+ microservices using OpenTelemetry.",
      "How do you build a golden path for new services that enforces security and observability standards?",
      "Describe your incident management process from alert to postmortem for a P0 outage.",
      "How would you implement immutable infrastructure and eliminate configuration drift?",
      "Explain FinOps practices for cloud cost visibility, allocation, and optimization.",
      "How do you design a secrets rotation strategy without application downtime?",
      "Describe how you'd implement compliance-as-code for SOC 2 or ISO 27001 controls.",
      "How would you build a multi-cloud networking architecture with consistent security policies?",
      "Explain your approach to platform engineering: abstractions, developer experience, and paved roads.",
    ],
  },

  // ────────────────────────────────────────────────────────────
  // DATA SCIENTIST
  // ────────────────────────────────────────────────────────────
  'Data Scientist': {
    fresher: [
      "What is the difference between supervised and unsupervised learning?",
      "What is a training set, validation set, and test set? Why do we need all three?",
      "What is overfitting? How do you detect it?",
      "What is a confusion matrix? Explain precision, recall, and F1-score.",
      "What is linear regression? What does the model equation represent?",
      "What is the difference between classification and regression problems?",
      "What is a decision tree? How does it split data?",
      "What is normalization vs standardization? When would you use each?",
      "What is a feature? What is feature engineering?",
      "What is cross-validation? Explain k-fold cross-validation.",
      "What is the difference between correlation and regression?",
      "What is a null hypothesis? What does it mean to reject it?",
      "What is a p-value? What is a common threshold for significance?",
      "What is Python pandas? What are DataFrames and Series?",
      "What is numpy? Why is it used in data science?",
      "What is scikit-learn? Name three algorithms it provides.",
      "What is the bias-variance trade-off at a basic level?",
      "What is one-hot encoding? Why is it needed for categorical variables?",
      "What is missing data imputation? Name two strategies.",
      "What is a scatter plot? What does it show about two variables?",
      "What is the difference between mean squared error and mean absolute error?",
      "What is a neural network? What is a neuron?",
      "What is dimensionality reduction? What is PCA?",
      "What is k-means clustering?",
      "What is the difference between a parametric and non-parametric model?",
    ],
    junior: [
      "Explain the bias-variance trade-off and how it affects model selection.",
      "How do you handle class imbalance in a classification problem?",
      "Compare Random Forest vs Gradient Boosting: strengths, weaknesses, and when to use each.",
      "How would you design a feature engineering pipeline for a recommendation system?",
      "How do you detect and handle data drift in a production ML model?",
      "How would you explain a complex ML model's predictions to non-technical stakeholders?",
      "Explain regularization: what is L1 (Lasso) vs L2 (Ridge) and when do you use each?",
      "What is the ROC-AUC score? When is it a better metric than accuracy?",
      "Explain how gradient descent works. What is the learning rate?",
      "What is feature importance? How does Random Forest compute it?",
      "Explain the difference between bagging and boosting ensemble methods.",
      "What is the curse of dimensionality? How does it affect distance-based algorithms?",
      "How would you approach a problem where you have very limited labeled data?",
      "What is hyperparameter tuning? Explain GridSearch vs RandomSearch vs Bayesian optimization.",
      "Explain t-SNE for dimensionality reduction. What are its limitations?",
      "How would you detect and remove outliers in a dataset?",
      "What is the silhouette score for clustering? How do you choose the right k in k-means?",
      "Explain precision-recall trade-off. How do you choose the right threshold?",
      "What is transfer learning? Give a real-world example.",
      "Explain time series cross-validation: why standard k-fold doesn't work.",
      "How do you handle high-cardinality categorical features?",
      "What is SHAP (SHapley Additive exPlanations)? How does it explain model predictions?",
      "Explain the difference between collaborative filtering and content-based recommendation.",
      "What is a pipeline in scikit-learn and why is it important for reproducibility?",
      "How would you validate a predictive model before deploying it to production?",
    ],
    senior: [
      "Explain the Transformer architecture and self-attention mechanism in detail.",
      "How would you design an A/B testing framework for evaluating a new ML model in production?",
      "Describe your approach to building a production ML system from data ingestion to model serving.",
      "How do you implement online learning for a recommendation system that handles concept drift?",
      "Compare fine-tuning vs RAG (Retrieval-Augmented Generation) for enterprise LLM applications.",
      "Explain causal inference methods: propensity score matching, instrumental variables, DiD.",
      "How would you design a fraud detection system with explainability requirements?",
      "Describe your approach to model monitoring and retraining in a production ML pipeline.",
      "How do you handle the ethical implications of a biased ML model in production?",
      "Explain federated learning: how does it enable model training without centralizing data?",
      "How would you build a real-time feature store serving models at low latency?",
      "Describe your approach to multi-objective optimization in a recommendation system.",
      "How do you implement uncertainty quantification for mission-critical ML models?",
      "Explain your strategy for model versioning, experiment tracking, and reproducibility at scale.",
      "How would you design a model explainability framework for regulatory compliance?",
      "Describe how you'd build a large-scale NLP pipeline for entity extraction and classification.",
      "Explain the mathematical intuition behind UMAP vs t-SNE for high-dimensional visualization.",
      "How would you implement a multi-armed bandit for personalized content ranking?",
      "Describe your approach to training a model with noisy labels at scale.",
      "How do you architect an end-to-end ML platform for 50+ data scientists?",
      "Explain graph neural networks and a domain where they outperform traditional approaches.",
      "How would you build a counterfactual evaluation framework for a recommendation system?",
      "Describe your approach to adversarial robustness testing for a deployed ML model.",
      "How do you implement privacy-preserving machine learning (differential privacy)?",
      "Explain your approach to productionizing an LLM with latency SLA requirements.",
    ],
  },

  // ────────────────────────────────────────────────────────────
  // PRODUCT MANAGER
  // ────────────────────────────────────────────────────────────
  'Product Manager': {
    fresher: [
      "What is product management? How does a PM differ from a project manager?",
      "What is a user story? Write one for a shopping cart feature.",
      "What is an MVP (Minimum Viable Product)? Why does it matter?",
      "What is a product roadmap? What does it contain?",
      "What is a KPI? Give three examples of product KPIs.",
      "What is user research? Name three methods for gathering user feedback.",
      "What is agile methodology? What is a sprint?",
      "What is a persona in product development?",
      "What is the difference between a feature and a product requirement?",
      "What is a product backlog? How do you prioritize it?",
      "What is the difference between qualitative and quantitative data in product decisions?",
      "What is A/B testing at a product level?",
      "What does 'product-market fit' mean?",
      "What is a north star metric? Give an example for a ride-sharing app.",
      "What is a stakeholder? How do you handle conflicting stakeholder opinions?",
      "What is an OKR? Write an example for a messaging product.",
      "What is user churn? How would you measure it?",
      "What is the difference between a bug and a feature request?",
      "Explain the product development lifecycle from ideation to launch.",
      "What is a competitive analysis? Why do PMs conduct one?",
      "What is retention in product terms? Why is it important?",
      "What is a go-to-market strategy?",
      "What is a net promoter score (NPS)?",
      "What makes a good product requirement document (PRD)?",
      "What is the difference between a PM's role in a startup vs a large company?",
    ],
    junior: [
      "How do you prioritize competing feature requests from enterprise sales vs technical debt?",
      "Walk me through designing a telemetry and metrics framework for a new AI feature.",
      "How do you balance user experience simplification against advanced power-user functionality?",
      "How would you conduct user research to validate a B2B SaaS product hypothesis?",
      "Describe your framework for making build-vs-buy decisions for platform capabilities.",
      "How would you define success metrics for a new social feature in a consumer app?",
      "Explain how you'd handle a situation where engineering says a feature will take 3x longer than expected.",
      "How do you measure product-market fit quantitatively?",
      "Describe how you'd approach launching a feature to 5% of users first.",
      "How would you investigate why a key metric dropped 20% last week?",
      "Explain the RICE prioritization framework with a real product example.",
      "How do you write a product spec that engineering can build from?",
      "Describe your approach to managing technical debt on the product roadmap.",
      "How do you structure a product review meeting with leadership?",
      "Explain how you'd define the north star metric for a marketplace platform.",
      "What is a customer journey map? How do you use it to prioritize features?",
      "How would you respond if a major customer threatens to churn over a missing feature?",
      "Describe the process of running a usability test and incorporating findings.",
      "How do you align engineering, design, and business stakeholders on a product decision?",
      "Explain how you'd approach pricing a new premium tier for a freemium product.",
      "What is the difference between a leading indicator and a lagging indicator in product analytics?",
      "How would you handle a feature that your data says is popular but users say they hate?",
      "Explain how you structure a product launch checklist.",
      "How do you identify which user segment to focus on for a growth initiative?",
      "Describe how you'd create a feedback loop between customer support data and product decisions.",
    ],
    senior: [
      "How do you build a 3-year product strategy that aligns with business goals and market trends?",
      "Describe how you'd turnaround a product that has stagnating growth.",
      "How do you build a culture of data-driven product decisions in an organization?",
      "Explain how you'd structure and scale a product organization from 5 to 50 PMs.",
      "How do you balance platform work (APIs, infrastructure) vs user-facing features on a roadmap?",
      "Describe your framework for making large platform bets (e.g., enter a new market, sunset a product).",
      "How would you define and evolve the product vision for a mature B2B product?",
      "Explain how you'd approach building an internal AI tooling product for an enterprise.",
      "How do you handle a board or CEO who insists on shipping a feature you believe is wrong?",
      "Describe your approach to running executive-level product reviews and business cases.",
      "How would you design a monetization strategy for a product that was previously free?",
      "Explain how you'd manage a product portfolio with multiple competing product lines.",
      "How do you build a product council or review process that balances speed and quality?",
      "Describe how you'd identify and respond to a competitive threat from a new market entrant.",
      "How would you implement a product operations function to improve PM effectiveness?",
      "Explain your approach to building network effects into a marketplace product.",
      "How do you structure an experimentation program to maximize learning velocity?",
      "Describe how you'd build a partner ecosystem strategy for a platform product.",
      "How would you approach international expansion for a product built for the US market?",
      "Explain how to measure and communicate the ROI of product investments to the CFO.",
      "How do you build a product intuition for an entirely new market or domain?",
      "Describe your approach to managing innovation alongside operational excellence in product.",
      "How would you redesign the product development process to be more customer-centric?",
      "Explain how you'd handle a high-priority regulatory requirement that conflicts with product strategy.",
      "Describe your framework for deciding when to kill a product or feature.",
    ],
  },

  // ────────────────────────────────────────────────────────────
  // CYBERSECURITY ANALYST
  // ────────────────────────────────────────────────────────────
  'Cybersecurity Analyst': {
    fresher: [
      "What is cybersecurity? What are the three pillars of the CIA triad?",
      "What is the difference between authentication and authorization?",
      "What is a firewall? What does it protect against?",
      "What is malware? Name five types of malware.",
      "What is phishing? How does a phishing attack work?",
      "What is a VPN? How does it protect network traffic?",
      "What is encryption? What is the difference between symmetric and asymmetric encryption?",
      "What is the difference between HTTP and HTTPS?",
      "What is a digital certificate? What is its purpose?",
      "What is multi-factor authentication (MFA)?",
      "What is a vulnerability? What is a CVE?",
      "What is the difference between a virus and a worm?",
      "What is social engineering in cybersecurity?",
      "What is a brute force attack? How can it be prevented?",
      "What is a DDoS attack? How does it work?",
      "What is the principle of least privilege?",
      "What is a patch? Why is patch management important?",
      "What is a security audit?",
      "What is a port scan? What tool is commonly used?",
      "What is the difference between a black hat and a white hat hacker?",
      "What is an IDS and IPS? How do they differ?",
      "What is a security information and event management (SIEM) system?",
      "What is a honeypot in cybersecurity?",
      "What is the difference between vulnerability assessment and penetration testing?",
      "What is the NIST Cybersecurity Framework?",
    ],
    junior: [
      "Walk through your incident response process for a suspected data breach.",
      "Explain the OWASP Top 10 and which vulnerabilities you consider most critical today.",
      "How would you implement a zero-trust security architecture for a cloud-native application?",
      "Describe the difference between symmetric and asymmetric encryption with real-world use cases.",
      "Explain how TLS 1.3 improves upon TLS 1.2 and what the key handshake differences are.",
      "How do you design a SIEM strategy for detecting advanced persistent threats (APTs)?",
      "Explain SQL injection: how does it work and how do you prevent it?",
      "What is cross-site scripting (XSS)? Explain reflected vs stored vs DOM-based XSS.",
      "How would you conduct a security assessment of a new third-party API integration?",
      "Explain the difference between defense in depth and least privilege as security strategies.",
      "What is a man-in-the-middle attack? How does certificate pinning prevent it?",
      "How do you perform log analysis for anomaly detection in a SIEM?",
      "Explain how you'd harden a Linux server for production use.",
      "What is PKI (Public Key Infrastructure)? Explain how certificate chains work.",
      "How would you respond to a ransomware incident?",
      "Explain how OAuth 2.0 flows work and what security vulnerabilities can arise.",
      "What is LDAP injection and how do you prevent it?",
      "How do you conduct a network vulnerability scan using tools like Nessus or OpenVAS?",
      "Explain the difference between black box, white box, and grey box penetration testing.",
      "What is a WAF? What can it detect that a traditional firewall cannot?",
      "How do you set up and tune alerting rules in a SIEM to reduce false positives?",
      "Explain how secure coding practices prevent buffer overflow vulnerabilities.",
      "What is SSRF (Server-Side Request Forgery)? How would you detect and prevent it?",
      "Explain how DNS can be used as an attack vector (DNS poisoning, DNS tunneling).",
      "How would you implement security baseline hardening for cloud workloads?",
    ],
    senior: [
      "Design a security architecture for a zero-trust enterprise network from scratch.",
      "Explain advanced persistent threats (APTs): how do you detect and respond to a multi-stage intrusion?",
      "Describe your approach to building a threat intelligence program for a large organization.",
      "How would you design a Security Operations Center (SOC) for a global financial institution?",
      "Explain how you'd implement a deception technology strategy using honeypots and honeytokens.",
      "Describe your approach to supply chain security: SBOM, dependency auditing, artifact signing.",
      "How do you design a red team exercise? What is the purple team approach?",
      "Explain how you'd implement a data loss prevention (DLP) strategy for a hybrid cloud environment.",
      "Describe your approach to threat modeling for a new product using STRIDE or PASTA.",
      "How would you build a security champion program to embed security in engineering teams?",
      "Explain your approach to achieving and maintaining SOC 2 Type II compliance.",
      "How do you design an incident response playbook for a cloud-native environment?",
      "Describe how you'd implement continuous security monitoring with automated remediation.",
      "How would you respond to an insider threat incident with limited evidence?",
      "Explain how you'd design a privileged access management (PAM) system for a large enterprise.",
      "Describe your approach to container security: image scanning, runtime protection, network policies.",
      "How would you implement security observability at scale using eBPF?",
      "Explain your framework for security risk quantification using FAIR methodology.",
      "How do you design a security chaos engineering program to test incident response?",
      "Describe how you'd build a vulnerability management program prioritizing by business risk.",
      "How would you architect a GDPR-compliant security incident notification process?",
      "Explain your approach to cryptography key management in a multi-cloud environment.",
      "How would you implement a security data lake for large-scale threat detection?",
      "Describe your strategy for securing an OT/ICS environment alongside corporate IT.",
      "How do you measure and report on the effectiveness of a security program to the board?",
    ],
  },

  // ────────────────────────────────────────────────────────────
  // UI/UX DESIGNER
  // ────────────────────────────────────────────────────────────
  'UI/UX Designer': {
    fresher: [
      "What is the difference between UI design and UX design?",
      "What is a wireframe? How does it differ from a mockup and a prototype?",
      "What is user-centered design?",
      "What is a persona in UX? How is one created?",
      "What are heuristic evaluation principles? Name three Nielsen's heuristics.",
      "What is information architecture? Why does it matter?",
      "What is a user journey map?",
      "What is Figma? What are its main features for UI design?",
      "What is the F-pattern and Z-pattern in visual layout? How do they guide design?",
      "What is the difference between navigation patterns (tabs, hamburger menu, sidebar)?",
      "What is contrast ratio? Why is it important for accessibility?",
      "What are affordances in UX design?",
      "What is a design system? Name two well-known design systems.",
      "What is the difference between serif and sans-serif fonts? When would you use each?",
      "What is responsive design?",
      "What is usability testing? What does it measure?",
      "What is the Gestalt principle of proximity?",
      "What is a call to action (CTA)? What makes a good CTA?",
      "What is the color wheel? What is the difference between complementary and analogous colors?",
      "What is white space (negative space) and why is it important in design?",
      "What is typography hierarchy?",
      "What is a grid system in design?",
      "What is WCAG and why does it matter?",
      "What is the difference between low-fidelity and high-fidelity prototypes?",
      "What tools do UX designers use besides Figma?",
    ],
    junior: [
      "How do you build and maintain a scalable design system for a large product team?",
      "Explain Gestalt principles and how they influence UI layout decisions.",
      "How do you conduct and synthesize usability testing results into actionable improvements?",
      "How do you measure the success of a design change quantitatively?",
      "Explain information architecture: how do you organize content for complex applications?",
      "How do you handle design-development handoff to ensure pixel-perfect implementation?",
      "Describe your process for designing micro-interactions that enhance user experience.",
      "How do you balance aesthetics and usability when they conflict?",
      "Explain how you approach accessibility (WCAG 2.1 AA) from the start of a design project.",
      "How would you redesign a confusing checkout flow? Walk through your process.",
      "What is component-driven design? How does Atomic Design methodology work?",
      "Explain how you'd conduct a card sorting exercise for information architecture.",
      "How do you design for error states and empty states in a UI?",
      "Describe how you'd approach a dark mode design variant for an existing product.",
      "Explain how you validate a design hypothesis before committing to full development.",
      "How do you design for mobile-first? What changes compared to desktop-first?",
      "What is cognitive load in UX? How do you reduce it in a complex dashboard?",
      "Describe how you'd approach a redesign of a feature that users find confusing.",
      "How do you present design decisions to non-design stakeholders?",
      "Explain the role of animation in UX: when does it help vs when does it distract?",
      "What is participatory design? Have you used it in a project?",
      "How would you design an onboarding flow for a new complex software product?",
      "What is eye tracking? How can the data inform design decisions?",
      "Explain how you prioritize accessibility features when the team has limited time.",
      "How would you design for users with different levels of technical literacy?",
    ],
    senior: [
      "How do you build a design organization culture that balances creativity with business outcomes?",
      "Describe your approach to establishing a shared design language across multiple products.",
      "How do you measure the ROI of UX design investments for executive stakeholders?",
      "Explain how you'd lead a large-scale product redesign while maintaining business continuity.",
      "How do you set up a continuous discovery program for user research at scale?",
      "Describe your framework for making design decisions in ambiguous, high-stakes situations.",
      "How would you build a design system that scales to 20+ product teams globally?",
      "Explain how you integrate accessibility as a non-negotiable standard across a design organization.",
      "How do you handle design leadership when engineering says your designs aren't feasible?",
      "Describe your approach to building a service design practice in an organization.",
      "How would you design a voice/conversational interface for a complex enterprise product?",
      "Explain how design thinking principles apply to organizational process redesign.",
      "How do you structure a design critique process that improves quality without blocking velocity?",
      "Describe how you'd introduce design operations (DesignOps) in a fast-growing company.",
      "How would you build and maintain a UX research repository for institutional knowledge?",
      "Explain how you approach cross-cultural design for a product serving 50+ countries.",
      "How do you create alignment between product strategy and user experience vision?",
      "Describe how you'd redesign a core workflow with thousands of daily active users.",
      "How would you build a design council to influence engineering and product priorities?",
      "Explain your approach to ethical design: dark patterns, persuasive technology, privacy.",
      "How do you make the case for qualitative research when leadership only trusts quantitative data?",
      "Describe how you'd design for emerging interaction paradigms (AR, VR, spatial computing).",
      "How would you hire and grow a world-class design team from scratch?",
      "Explain how you'd design an AI-assisted feature in a way that maintains user trust.",
      "How do you build a design culture where everyone — not just designers — cares about UX?",
    ],
  },

  // ────────────────────────────────────────────────────────────
  // MOBILE DEVELOPER
  // ────────────────────────────────────────────────────────────
  'Mobile Developer': {
    fresher: [
      "What is the difference between native, hybrid, and cross-platform mobile apps?",
      "What is React Native? How does it differ from building a native iOS or Android app?",
      "What is Flutter? What language does it use?",
      "What is the Android Activity lifecycle? Name the main states.",
      "What is a View in Android or a UIView in iOS?",
      "What is the difference between portrait and landscape orientation?",
      "What is a mobile app manifest (AndroidManifest.xml or Info.plist)?",
      "What is an APK? What is an IPA?",
      "What is the difference between an emulator and a physical device for testing?",
      "What is deep linking? What is a URL scheme?",
      "What is push notification? What is APNs vs FCM?",
      "What is the difference between foreground and background app states?",
      "What is a RecyclerView in Android?",
      "What is the difference between async and sync network calls in mobile?",
      "What is local storage in mobile apps? Name two ways to store data.",
      "What are permissions in mobile apps? Give three examples.",
      "What is the difference between Android and iOS design guidelines?",
      "What is a mobile app release? What is the Google Play Store vs Apple App Store process?",
      "What is crash reporting? Name a tool used for mobile crash tracking.",
      "What is a gesture in mobile UX? Name three common gestures.",
      "What is the difference between a fragment (Android) and a view controller (iOS)?",
      "What is responsive layout in mobile development?",
      "What is app signing? Why is it needed?",
      "What is a beta distribution channel (TestFlight/Firebase App Distribution)?",
      "What is the difference between debug and release builds?",
    ],
    junior: [
      "Compare React Native vs Flutter: rendering architecture, performance, and ecosystem trade-offs.",
      "How do you diagnose and fix UI jank (dropped frames) in a mobile application?",
      "Explain how push notifications work end-to-end (APNs/FCM, token management, payload handling).",
      "How would you implement offline-first data synchronization for a mobile app?",
      "Describe your approach to managing app state in a large React Native application.",
      "Explain deep linking and universal links: how do they work across iOS and Android?",
      "How would you architect a mobile app for accessibility compliance?",
      "How do you handle backward compatibility when releasing new app versions?",
      "Explain how you'd implement biometric authentication (Face ID, fingerprint) in a mobile app.",
      "How does memory management differ between iOS (ARC) and Android (garbage collection)?",
      "What is app backgrounding in iOS? Explain background fetch and background processing.",
      "How do you implement secure storage of sensitive data in a mobile app?",
      "Explain how mobile apps communicate with a backend API securely (certificate pinning).",
      "How would you handle complex navigation patterns in a large React Native app?",
      "Explain the difference between local and remote push notifications.",
      "How do you implement efficient image loading and caching in a mobile app?",
      "What is the bridge in React Native and what are its performance implications?",
      "How would you set up automated testing for a React Native application?",
      "Explain how you handle different screen densities (DPI) across Android devices.",
      "How would you implement in-app purchases for both iOS and Android?",
      "Explain the Android ViewModel and how it survives configuration changes.",
      "How do you handle network connectivity changes gracefully in a mobile app?",
      "What is Hermes in React Native? What performance benefits does it provide?",
      "How would you implement a custom animated transition between screens?",
      "Explain how app size optimization works for both iOS and Android.",
    ],
    senior: [
      "Design a mobile architecture for a large-scale super-app serving 50 million users.",
      "Explain how you'd implement React Native's New Architecture (JSI, Fabric, TurboModules).",
      "Describe your strategy for achieving consistent 60fps performance in a complex React Native app.",
      "How would you design a modular mobile architecture that enables 20+ teams to work independently?",
      "Explain how you'd implement real-time features (chat, live updates) at scale in a mobile app.",
      "Describe your approach to mobile security: code obfuscation, root/jailbreak detection, tamper detection.",
      "How do you architect a mobile app for offline-first with conflict resolution across devices?",
      "Explain your strategy for reducing app bundle size below 10MB for emerging markets.",
      "How would you build a mobile SDK that third-party apps can integrate reliably?",
      "Describe your approach to managing a mobile platform team supporting multiple product teams.",
      "How do you implement a mobile CI/CD pipeline with automated build, test, and release?",
      "Explain how you'd architect a mobile app that works seamlessly on phones, tablets, and foldables.",
      "How would you implement machine learning inference on-device using Core ML or TensorFlow Lite?",
      "Describe your approach to A/B testing and feature flagging in a mobile application.",
      "How do you build a mobile performance monitoring system with custom metrics?",
      "Explain your strategy for managing breaking API changes that affect multiple app versions in the wild.",
      "How would you design a seamless handoff experience between mobile and desktop in an ecosystem app?",
      "Describe how you'd implement dynamic content delivery in a mobile app without a forced update.",
      "How do you handle compliance requirements (GDPR, CCPA) in mobile app data collection?",
      "Explain how you'd build a custom render engine for a highly interactive mobile game-like UI.",
      "Describe your approach to zero-crash engineering for a consumer mobile application.",
      "How would you architect push notification infrastructure for 100 million devices?",
      "Explain your strategy for code sharing between iOS, Android, and web platforms.",
      "How do you build and scale a mobile release process with 100+ engineers contributing?",
      "Describe how you'd implement predictive pre-fetching to improve perceived performance.",
    ],
  },

};

// ────────────────────────────────────────────────────────────
// GENERIC FALLBACK for roles not in the bank above
// ────────────────────────────────────────────────────────────
const GENERIC_QUESTIONS = {
  fresher: [
    "Tell me about yourself and why you chose this career path.",
    "What do you consider your greatest technical strength?",
    "Describe a project you built — what was your role and what did you learn?",
    "What programming languages or tools are you most comfortable with? Why?",
    "How do you approach learning a completely new technology?",
    "Describe a time you encountered a bug. How did you debug it?",
    "What is version control? Have you used Git?",
    "What are your long-term career goals in this field?",
    "What resources do you use to stay current with industry trends?",
    "Describe a team project: how did you contribute and handle disagreements?",
    "What is your approach when you don't know the answer to a problem?",
    "Why do you want to work for this company specifically?",
    "What was your biggest learning from your academic or personal projects?",
    "How do you handle tight deadlines and multiple competing tasks?",
    "What interests you most about this specific role?",
  ],
  junior: [
    "Describe the most complex technical project you've worked on.",
    "Explain a technical decision you made and the trade-offs you considered.",
    "How do you approach code reviews — both giving and receiving feedback?",
    "Describe a time you disagreed with a technical decision. How did you handle it?",
    "How do you ensure your code is maintainable by other engineers?",
    "What is your approach to writing tests? What types do you prioritize?",
    "Describe a production incident you were involved in. What did you learn?",
    "How do you break down a large, ambiguous technical task?",
    "What is your approach to documentation?",
    "Describe a time you had to learn a new technology quickly under pressure.",
    "How do you stay up to date with best practices in your domain?",
    "Describe a refactoring initiative you led or contributed to.",
    "How do you balance speed of delivery vs code quality?",
    "Explain a performance optimization you implemented with measurable impact.",
    "How do you handle scope creep during a project?",
  ],
  senior: [
    "Describe a large-scale system you designed from scratch. What trade-offs did you make?",
    "How do you approach technical mentorship and growing junior engineers?",
    "Describe your experience influencing engineering culture or process changes.",
    "How do you make build vs buy decisions for major technical infrastructure?",
    "Describe your approach to setting technical vision for a team or organization.",
    "How do you manage technical debt while delivering business value?",
    "Describe a situation where you had to push back on leadership on a technical decision.",
    "How do you structure your team's engineering principles and decision-making process?",
    "Describe your approach to cross-team alignment on shared technical standards.",
    "How do you evaluate and introduce new technologies to your stack responsibly?",
    "Describe a time you led an organization through a major technical migration.",
    "How do you build psychological safety in a high-performance engineering team?",
    "Describe your approach to hiring and building a world-class engineering team.",
    "How do you communicate technical risks to executive stakeholders?",
    "What does engineering excellence mean to you, and how do you create it?",
  ],
};

/**
 * Get a unique question for a given role, experience level, and session.
 * Tracks usedQuestionIds within the session to guarantee no repeats.
 *
 * @param {object} params
 * @param {string} params.role - Job role
 * @param {string} params.experienceLevel - 'fresher' | 'junior' | 'mid' | 'senior'
 * @param {Set<string>} params.usedQuestions - Set of already-used question texts
 * @returns {{ question: string|null, found: boolean }}
 */
function getUniqueQuestion(role, experienceLevel, usedQuestions) {
  // Normalize experience level
  const level = ['fresher', 'junior'].includes(experienceLevel)
    ? experienceLevel
    : ['mid'].includes(experienceLevel)
    ? 'junior'
    : 'senior';

  // Find role bank (exact match or fuzzy match)
  let roleBank = null;
  const normalizedRole = role.trim();

  if (QUESTION_BANK[normalizedRole]) {
    roleBank = QUESTION_BANK[normalizedRole];
  } else {
    // Fuzzy match: check if the role contains a bank key or vice versa
    for (const bankKey of Object.keys(QUESTION_BANK)) {
      if (
        normalizedRole.toLowerCase().includes(bankKey.toLowerCase()) ||
        bankKey.toLowerCase().includes(normalizedRole.toLowerCase())
      ) {
        roleBank = QUESTION_BANK[bankKey];
        break;
      }
    }
  }

  const pool = roleBank ? roleBank[level] || roleBank['junior'] : GENERIC_QUESTIONS[level] || GENERIC_QUESTIONS['junior'];

  // Shuffle for randomness and find first unused
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  for (const q of shuffled) {
    if (!usedQuestions.has(q)) {
      return { question: q, found: true };
    }
  }

  // All questions used — fall back to generic pool
  const genericPool = GENERIC_QUESTIONS[level];
  for (const q of genericPool) {
    if (!usedQuestions.has(q)) {
      return { question: q, found: true };
    }
  }

  return { question: null, found: false };
}

/**
 * Returns a list of all available roles in the question bank.
 */
function getAvailableRoles() {
  return Object.keys(QUESTION_BANK);
}

module.exports = { getUniqueQuestion, getAvailableRoles, QUESTION_BANK };
